### ISSUE TITLE
Any chance you gotta demo of this?

### ISSUE THREAD

**Issue by ScriptedAlchemy** [mockingbot/custom-split-chunk-webpack-plugin#1]
Hey! I'm having a little challenge understanding your docs well. 

Basically, I found a way to load code from separate webpack builds and unite their client-side manifests. (imagine DLL plugin but on the client side and fully orchestrated. 

I've been looking for a good way to split chunks out, not using the splitChunks API, but rather via a plugin. Yours seems to do this but its a little hard (and rightfully so) so quite understand how it all stitched together. any chance you've got a little demo repo or would be willing to make one?

**Comment by ThatBean** [comment]
The demo is actually test..

For the code you can check the file under [test/](https://github.com/mockingbot/custom-split-chunk-webpack-plugin/tree/master/test)

Sample output can be found at [travis-ci](https://travis-ci.org/mockingbot/custom-split-chunk-webpack-plugin) (where test runs)

And you can test the `test/` files locally with `npm i && npm test`

**Comment by ScriptedAlchemy** [comment]
Thank you! appreciate it!
